// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameState.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MHUrho.Storage {

  /// <summary>Holder for reflection information generated from GameState.proto</summary>
  public static partial class GameStateReflection {

    #region Descriptor
    /// <summary>File descriptor for GameState.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameStateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9HYW1lU3RhdGUucHJvdG8SDk1IVXJoby5TdG9yYWdlGg9VcmhvVHlwZXMu",
            "cHJvdG8aE1BsdWdpblN0b3JhZ2UucHJvdG8iiQIKB1N0TGV2ZWwSIgoDbWFw",
            "GAEgASgLMhUuTUhVcmhvLlN0b3JhZ2UuU3RNYXASJQoFdW5pdHMYAiADKAsy",
            "Fi5NSFVyaG8uU3RvcmFnZS5TdFVuaXQSLQoJYnVpbGRpbmdzGAMgAygLMhou",
            "TUhVcmhvLlN0b3JhZ2UuU3RCdWlsZGluZxIpCgdwbGF5ZXJzGAQgAygLMhgu",
            "TUhVcmhvLlN0b3JhZ2UuU3RQbGF5ZXISMQoLcHJvamVjdGlsZXMYBSADKAsy",
            "HC5NSFVyaG8uU3RvcmFnZS5TdFByb2plY3RpbGUSEQoJZ2FtZVNwZWVkGAYg",
            "ASgCEhMKC3BhY2thZ2VOYW1lGAcgASgJIowBCgZTdFRpbGUSDwoHdW5pdElE",
            "cxgCIAMoBRISCgp0aWxlVHlwZUlEGAMgASgFEjUKD3RvcExlZnRQb3NpdGlv",
            "bhgEIAEoCzIcLk1IVXJoby5TdG9yYWdlLlN0SW50VmVjdG9yMhIOCgZoZWln",
            "aHQYBSABKAISFgoOc3BsaXREaXJlY3Rpb24YBiABKAgizwEKDFN0Qm9yZGVy",
            "VGlsZRISCgp0aWxlVHlwZUlEGAEgASgFEjUKD3RvcExlZnRQb3NpdGlvbhgC",
            "IAEoCzIcLk1IVXJoby5TdG9yYWdlLlN0SW50VmVjdG9yMhIVCg10b3BMZWZ0",
            "SGVpZ2h0GAMgASgCEhYKDnRvcFJpZ2h0SGVpZ2h0GAQgASgCEhUKDWJvdExl",
            "ZnRIZWlnaHQYBSABKAISFgoOYm90UmlnaHRIZWlnaHQYBiABKAISFgoOc3Bs",
            "aXREaXJlY3Rpb24YByABKAgiTgoLU3RNYXBUYXJnZXQSEgoKaW5zdGFuY2VJ",
            "RBgBIAEoBRIrCghwb3NpdGlvbhgCIAEoCzIZLk1IVXJoby5TdG9yYWdlLlN0",
            "VmVjdG9yMyLSAgoGU3RVbml0EgoKAmlkGAEgASgFEg4KBnR5cGVJRBgCIAEo",
            "BRIrCghwb3NpdGlvbhgDIAEoCzIZLk1IVXJoby5TdG9yYWdlLlN0VmVjdG9y",
            "MxIQCghwbGF5ZXJJRBgEIAEoBRIUCgx0YXJnZXRVbml0SUQYBSABKAUSLgoK",
            "dXNlclBsdWdpbhgGIAEoCzIaLk1IVXJoby5TdG9yYWdlLlBsdWdpbkRhdGES",
            "TgoUZGVmYXVsdENvbXBvbmVudERhdGEYByADKAsyMC5NSFVyaG8uU3RvcmFn",
            "ZS5TdFVuaXQuRGVmYXVsdENvbXBvbmVudERhdGFFbnRyeRpXChlEZWZhdWx0",
            "Q29tcG9uZW50RGF0YUVudHJ5EgsKA2tleRgBIAEoBRIpCgV2YWx1ZRgCIAEo",
            "CzIaLk1IVXJoby5TdG9yYWdlLlBsdWdpbkRhdGE6AjgBIsgCCgxTdFByb2pl",
            "Y3RpbGUSCgoCaWQYASABKAUSDgoGdHlwZUlEGAIgASgFEisKCHBvc2l0aW9u",
            "GAMgASgLMhkuTUhVcmhvLlN0b3JhZ2UuU3RWZWN0b3IzEhAKCHBsYXllcklE",
            "GAQgASgFEi4KCnVzZXJQbHVnaW4YBSABKAsyGi5NSFVyaG8uU3RvcmFnZS5Q",
            "bHVnaW5EYXRhElQKFGRlZmF1bHRDb21wb25lbnREYXRhGAYgAygLMjYuTUhV",
            "cmhvLlN0b3JhZ2UuU3RQcm9qZWN0aWxlLkRlZmF1bHRDb21wb25lbnREYXRh",
            "RW50cnkaVwoZRGVmYXVsdENvbXBvbmVudERhdGFFbnRyeRILCgNrZXkYASAB",
            "KAUSKQoFdmFsdWUYAiABKAsyGi5NSFVyaG8uU3RvcmFnZS5QbHVnaW5EYXRh",
            "OgI4ASLHAgoKU3RCdWlsZGluZxIKCgJpZBgBIAEoBRIOCgZ0eXBlSUQYAiAB",
            "KAUSLgoIbG9jYXRpb24YAyABKAsyHC5NSFVyaG8uU3RvcmFnZS5TdEludFZl",
            "Y3RvcjISEAoIcGxheWVySUQYBCABKAUSLgoKdXNlclBsdWdpbhgGIAEoCzIa",
            "Lk1IVXJoby5TdG9yYWdlLlBsdWdpbkRhdGESUgoUZGVmYXVsdENvbXBvbmVu",
            "dERhdGEYByADKAsyNC5NSFVyaG8uU3RvcmFnZS5TdEJ1aWxkaW5nLkRlZmF1",
            "bHRDb21wb25lbnREYXRhRW50cnkaVwoZRGVmYXVsdENvbXBvbmVudERhdGFF",
            "bnRyeRILCgNrZXkYASABKAUSKQoFdmFsdWUYAiABKAsyGi5NSFVyaG8uU3Rv",
            "cmFnZS5QbHVnaW5EYXRhOgI4ASKLAQoIU3RQbGF5ZXISEAoIcGxheWVySUQY",
            "ASABKAUSDwoHdW5pdElEcxgCIAMoBRITCgtidWlsZGluZ0lEcxgDIAMoBRIX",
            "Cg9mcmllbmRQbGF5ZXJJRHMYBCADKAUSLgoKdXNlclBsdWdpbhgFIAEoCzIa",
            "Lk1IVXJoby5TdG9yYWdlLlBsdWdpbkRhdGEiwwEKBVN0TWFwEioKBHNpemUY",
            "ASABKAsyHC5NSFVyaG8uU3RvcmFnZS5TdEludFZlY3RvcjISJQoFdGlsZXMY",
            "AiADKAsyFi5NSFVyaG8uU3RvcmFnZS5TdFRpbGUSMQoLYm9yZGVyVGlsZXMY",
            "AyADKAsyHC5NSFVyaG8uU3RvcmFnZS5TdEJvcmRlclRpbGUSNAoPbWFwUmFu",
            "Z2VUYXJnZXRzGAQgAygLMhsuTUhVcmhvLlN0b3JhZ2UuU3RNYXBUYXJnZXRi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MHUrho.Storage.UrhoTypesReflection.Descriptor, global::MHUrho.Storage.PluginStorageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MHUrho.Storage.StLevel), global::MHUrho.Storage.StLevel.Parser, new[]{ "Map", "Units", "Buildings", "Players", "Projectiles", "GameSpeed", "PackageName" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MHUrho.Storage.StTile), global::MHUrho.Storage.StTile.Parser, new[]{ "UnitIDs", "TileTypeID", "TopLeftPosition", "Height", "SplitDirection" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MHUrho.Storage.StBorderTile), global::MHUrho.Storage.StBorderTile.Parser, new[]{ "TileTypeID", "TopLeftPosition", "TopLeftHeight", "TopRightHeight", "BotLeftHeight", "BotRightHeight", "SplitDirection" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MHUrho.Storage.StMapTarget), global::MHUrho.Storage.StMapTarget.Parser, new[]{ "InstanceID", "Position" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MHUrho.Storage.StUnit), global::MHUrho.Storage.StUnit.Parser, new[]{ "Id", "TypeID", "Position", "PlayerID", "TargetUnitID", "UserPlugin", "DefaultComponentData" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::MHUrho.Storage.StProjectile), global::MHUrho.Storage.StProjectile.Parser, new[]{ "Id", "TypeID", "Position", "PlayerID", "UserPlugin", "DefaultComponentData" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::MHUrho.Storage.StBuilding), global::MHUrho.Storage.StBuilding.Parser, new[]{ "Id", "TypeID", "Location", "PlayerID", "UserPlugin", "DefaultComponentData" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::MHUrho.Storage.StPlayer), global::MHUrho.Storage.StPlayer.Parser, new[]{ "PlayerID", "UnitIDs", "BuildingIDs", "FriendPlayerIDs", "UserPlugin" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MHUrho.Storage.StMap), global::MHUrho.Storage.StMap.Parser, new[]{ "Size", "Tiles", "BorderTiles", "MapRangeTargets" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StLevel : pb::IMessage<StLevel> {
    private static readonly pb::MessageParser<StLevel> _parser = new pb::MessageParser<StLevel>(() => new StLevel());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StLevel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MHUrho.Storage.GameStateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StLevel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StLevel(StLevel other) : this() {
      Map = other.map_ != null ? other.Map.Clone() : null;
      units_ = other.units_.Clone();
      buildings_ = other.buildings_.Clone();
      players_ = other.players_.Clone();
      projectiles_ = other.projectiles_.Clone();
      gameSpeed_ = other.gameSpeed_;
      packageName_ = other.packageName_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StLevel Clone() {
      return new StLevel(this);
    }

    /// <summary>Field number for the "map" field.</summary>
    public const int MapFieldNumber = 1;
    private global::MHUrho.Storage.StMap map_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MHUrho.Storage.StMap Map {
      get { return map_; }
      set {
        map_ = value;
      }
    }

    /// <summary>Field number for the "units" field.</summary>
    public const int UnitsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::MHUrho.Storage.StUnit> _repeated_units_codec
        = pb::FieldCodec.ForMessage(18, global::MHUrho.Storage.StUnit.Parser);
    private readonly pbc::RepeatedField<global::MHUrho.Storage.StUnit> units_ = new pbc::RepeatedField<global::MHUrho.Storage.StUnit>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MHUrho.Storage.StUnit> Units {
      get { return units_; }
    }

    /// <summary>Field number for the "buildings" field.</summary>
    public const int BuildingsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::MHUrho.Storage.StBuilding> _repeated_buildings_codec
        = pb::FieldCodec.ForMessage(26, global::MHUrho.Storage.StBuilding.Parser);
    private readonly pbc::RepeatedField<global::MHUrho.Storage.StBuilding> buildings_ = new pbc::RepeatedField<global::MHUrho.Storage.StBuilding>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MHUrho.Storage.StBuilding> Buildings {
      get { return buildings_; }
    }

    /// <summary>Field number for the "players" field.</summary>
    public const int PlayersFieldNumber = 4;
    private static readonly pb::FieldCodec<global::MHUrho.Storage.StPlayer> _repeated_players_codec
        = pb::FieldCodec.ForMessage(34, global::MHUrho.Storage.StPlayer.Parser);
    private readonly pbc::RepeatedField<global::MHUrho.Storage.StPlayer> players_ = new pbc::RepeatedField<global::MHUrho.Storage.StPlayer>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MHUrho.Storage.StPlayer> Players {
      get { return players_; }
    }

    /// <summary>Field number for the "projectiles" field.</summary>
    public const int ProjectilesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::MHUrho.Storage.StProjectile> _repeated_projectiles_codec
        = pb::FieldCodec.ForMessage(42, global::MHUrho.Storage.StProjectile.Parser);
    private readonly pbc::RepeatedField<global::MHUrho.Storage.StProjectile> projectiles_ = new pbc::RepeatedField<global::MHUrho.Storage.StProjectile>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MHUrho.Storage.StProjectile> Projectiles {
      get { return projectiles_; }
    }

    /// <summary>Field number for the "gameSpeed" field.</summary>
    public const int GameSpeedFieldNumber = 6;
    private float gameSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float GameSpeed {
      get { return gameSpeed_; }
      set {
        gameSpeed_ = value;
      }
    }

    /// <summary>Field number for the "packageName" field.</summary>
    public const int PackageNameFieldNumber = 7;
    private string packageName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PackageName {
      get { return packageName_; }
      set {
        packageName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StLevel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StLevel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Map, other.Map)) return false;
      if(!units_.Equals(other.units_)) return false;
      if(!buildings_.Equals(other.buildings_)) return false;
      if(!players_.Equals(other.players_)) return false;
      if(!projectiles_.Equals(other.projectiles_)) return false;
      if (GameSpeed != other.GameSpeed) return false;
      if (PackageName != other.PackageName) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (map_ != null) hash ^= Map.GetHashCode();
      hash ^= units_.GetHashCode();
      hash ^= buildings_.GetHashCode();
      hash ^= players_.GetHashCode();
      hash ^= projectiles_.GetHashCode();
      if (GameSpeed != 0F) hash ^= GameSpeed.GetHashCode();
      if (PackageName.Length != 0) hash ^= PackageName.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (map_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Map);
      }
      units_.WriteTo(output, _repeated_units_codec);
      buildings_.WriteTo(output, _repeated_buildings_codec);
      players_.WriteTo(output, _repeated_players_codec);
      projectiles_.WriteTo(output, _repeated_projectiles_codec);
      if (GameSpeed != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(GameSpeed);
      }
      if (PackageName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(PackageName);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (map_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Map);
      }
      size += units_.CalculateSize(_repeated_units_codec);
      size += buildings_.CalculateSize(_repeated_buildings_codec);
      size += players_.CalculateSize(_repeated_players_codec);
      size += projectiles_.CalculateSize(_repeated_projectiles_codec);
      if (GameSpeed != 0F) {
        size += 1 + 4;
      }
      if (PackageName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PackageName);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StLevel other) {
      if (other == null) {
        return;
      }
      if (other.map_ != null) {
        if (map_ == null) {
          map_ = new global::MHUrho.Storage.StMap();
        }
        Map.MergeFrom(other.Map);
      }
      units_.Add(other.units_);
      buildings_.Add(other.buildings_);
      players_.Add(other.players_);
      projectiles_.Add(other.projectiles_);
      if (other.GameSpeed != 0F) {
        GameSpeed = other.GameSpeed;
      }
      if (other.PackageName.Length != 0) {
        PackageName = other.PackageName;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (map_ == null) {
              map_ = new global::MHUrho.Storage.StMap();
            }
            input.ReadMessage(map_);
            break;
          }
          case 18: {
            units_.AddEntriesFrom(input, _repeated_units_codec);
            break;
          }
          case 26: {
            buildings_.AddEntriesFrom(input, _repeated_buildings_codec);
            break;
          }
          case 34: {
            players_.AddEntriesFrom(input, _repeated_players_codec);
            break;
          }
          case 42: {
            projectiles_.AddEntriesFrom(input, _repeated_projectiles_codec);
            break;
          }
          case 53: {
            GameSpeed = input.ReadFloat();
            break;
          }
          case 58: {
            PackageName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class StTile : pb::IMessage<StTile> {
    private static readonly pb::MessageParser<StTile> _parser = new pb::MessageParser<StTile>(() => new StTile());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StTile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MHUrho.Storage.GameStateReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StTile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StTile(StTile other) : this() {
      unitIDs_ = other.unitIDs_.Clone();
      tileTypeID_ = other.tileTypeID_;
      TopLeftPosition = other.topLeftPosition_ != null ? other.TopLeftPosition.Clone() : null;
      height_ = other.height_;
      splitDirection_ = other.splitDirection_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StTile Clone() {
      return new StTile(this);
    }

    /// <summary>Field number for the "unitIDs" field.</summary>
    public const int UnitIDsFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_unitIDs_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> unitIDs_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> UnitIDs {
      get { return unitIDs_; }
    }

    /// <summary>Field number for the "tileTypeID" field.</summary>
    public const int TileTypeIDFieldNumber = 3;
    private int tileTypeID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TileTypeID {
      get { return tileTypeID_; }
      set {
        tileTypeID_ = value;
      }
    }

    /// <summary>Field number for the "topLeftPosition" field.</summary>
    public const int TopLeftPositionFieldNumber = 4;
    private global::MHUrho.Storage.StIntVector2 topLeftPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MHUrho.Storage.StIntVector2 TopLeftPosition {
      get { return topLeftPosition_; }
      set {
        topLeftPosition_ = value;
      }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 5;
    private float height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "splitDirection" field.</summary>
    public const int SplitDirectionFieldNumber = 6;
    private bool splitDirection_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool SplitDirection {
      get { return splitDirection_; }
      set {
        splitDirection_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StTile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StTile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!unitIDs_.Equals(other.unitIDs_)) return false;
      if (TileTypeID != other.TileTypeID) return false;
      if (!object.Equals(TopLeftPosition, other.TopLeftPosition)) return false;
      if (Height != other.Height) return false;
      if (SplitDirection != other.SplitDirection) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= unitIDs_.GetHashCode();
      if (TileTypeID != 0) hash ^= TileTypeID.GetHashCode();
      if (topLeftPosition_ != null) hash ^= TopLeftPosition.GetHashCode();
      if (Height != 0F) hash ^= Height.GetHashCode();
      if (SplitDirection != false) hash ^= SplitDirection.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      unitIDs_.WriteTo(output, _repeated_unitIDs_codec);
      if (TileTypeID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TileTypeID);
      }
      if (topLeftPosition_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TopLeftPosition);
      }
      if (Height != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Height);
      }
      if (SplitDirection != false) {
        output.WriteRawTag(48);
        output.WriteBool(SplitDirection);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += unitIDs_.CalculateSize(_repeated_unitIDs_codec);
      if (TileTypeID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TileTypeID);
      }
      if (topLeftPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TopLeftPosition);
      }
      if (Height != 0F) {
        size += 1 + 4;
      }
      if (SplitDirection != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StTile other) {
      if (other == null) {
        return;
      }
      unitIDs_.Add(other.unitIDs_);
      if (other.TileTypeID != 0) {
        TileTypeID = other.TileTypeID;
      }
      if (other.topLeftPosition_ != null) {
        if (topLeftPosition_ == null) {
          topLeftPosition_ = new global::MHUrho.Storage.StIntVector2();
        }
        TopLeftPosition.MergeFrom(other.TopLeftPosition);
      }
      if (other.Height != 0F) {
        Height = other.Height;
      }
      if (other.SplitDirection != false) {
        SplitDirection = other.SplitDirection;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 18:
          case 16: {
            unitIDs_.AddEntriesFrom(input, _repeated_unitIDs_codec);
            break;
          }
          case 24: {
            TileTypeID = input.ReadInt32();
            break;
          }
          case 34: {
            if (topLeftPosition_ == null) {
              topLeftPosition_ = new global::MHUrho.Storage.StIntVector2();
            }
            input.ReadMessage(topLeftPosition_);
            break;
          }
          case 45: {
            Height = input.ReadFloat();
            break;
          }
          case 48: {
            SplitDirection = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class StBorderTile : pb::IMessage<StBorderTile> {
    private static readonly pb::MessageParser<StBorderTile> _parser = new pb::MessageParser<StBorderTile>(() => new StBorderTile());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StBorderTile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MHUrho.Storage.GameStateReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StBorderTile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StBorderTile(StBorderTile other) : this() {
      tileTypeID_ = other.tileTypeID_;
      TopLeftPosition = other.topLeftPosition_ != null ? other.TopLeftPosition.Clone() : null;
      topLeftHeight_ = other.topLeftHeight_;
      topRightHeight_ = other.topRightHeight_;
      botLeftHeight_ = other.botLeftHeight_;
      botRightHeight_ = other.botRightHeight_;
      splitDirection_ = other.splitDirection_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StBorderTile Clone() {
      return new StBorderTile(this);
    }

    /// <summary>Field number for the "tileTypeID" field.</summary>
    public const int TileTypeIDFieldNumber = 1;
    private int tileTypeID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TileTypeID {
      get { return tileTypeID_; }
      set {
        tileTypeID_ = value;
      }
    }

    /// <summary>Field number for the "topLeftPosition" field.</summary>
    public const int TopLeftPositionFieldNumber = 2;
    private global::MHUrho.Storage.StIntVector2 topLeftPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MHUrho.Storage.StIntVector2 TopLeftPosition {
      get { return topLeftPosition_; }
      set {
        topLeftPosition_ = value;
      }
    }

    /// <summary>Field number for the "topLeftHeight" field.</summary>
    public const int TopLeftHeightFieldNumber = 3;
    private float topLeftHeight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float TopLeftHeight {
      get { return topLeftHeight_; }
      set {
        topLeftHeight_ = value;
      }
    }

    /// <summary>Field number for the "topRightHeight" field.</summary>
    public const int TopRightHeightFieldNumber = 4;
    private float topRightHeight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float TopRightHeight {
      get { return topRightHeight_; }
      set {
        topRightHeight_ = value;
      }
    }

    /// <summary>Field number for the "botLeftHeight" field.</summary>
    public const int BotLeftHeightFieldNumber = 5;
    private float botLeftHeight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float BotLeftHeight {
      get { return botLeftHeight_; }
      set {
        botLeftHeight_ = value;
      }
    }

    /// <summary>Field number for the "botRightHeight" field.</summary>
    public const int BotRightHeightFieldNumber = 6;
    private float botRightHeight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float BotRightHeight {
      get { return botRightHeight_; }
      set {
        botRightHeight_ = value;
      }
    }

    /// <summary>Field number for the "splitDirection" field.</summary>
    public const int SplitDirectionFieldNumber = 7;
    private bool splitDirection_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool SplitDirection {
      get { return splitDirection_; }
      set {
        splitDirection_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StBorderTile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StBorderTile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TileTypeID != other.TileTypeID) return false;
      if (!object.Equals(TopLeftPosition, other.TopLeftPosition)) return false;
      if (TopLeftHeight != other.TopLeftHeight) return false;
      if (TopRightHeight != other.TopRightHeight) return false;
      if (BotLeftHeight != other.BotLeftHeight) return false;
      if (BotRightHeight != other.BotRightHeight) return false;
      if (SplitDirection != other.SplitDirection) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TileTypeID != 0) hash ^= TileTypeID.GetHashCode();
      if (topLeftPosition_ != null) hash ^= TopLeftPosition.GetHashCode();
      if (TopLeftHeight != 0F) hash ^= TopLeftHeight.GetHashCode();
      if (TopRightHeight != 0F) hash ^= TopRightHeight.GetHashCode();
      if (BotLeftHeight != 0F) hash ^= BotLeftHeight.GetHashCode();
      if (BotRightHeight != 0F) hash ^= BotRightHeight.GetHashCode();
      if (SplitDirection != false) hash ^= SplitDirection.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TileTypeID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TileTypeID);
      }
      if (topLeftPosition_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TopLeftPosition);
      }
      if (TopLeftHeight != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(TopLeftHeight);
      }
      if (TopRightHeight != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(TopRightHeight);
      }
      if (BotLeftHeight != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(BotLeftHeight);
      }
      if (BotRightHeight != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(BotRightHeight);
      }
      if (SplitDirection != false) {
        output.WriteRawTag(56);
        output.WriteBool(SplitDirection);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TileTypeID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TileTypeID);
      }
      if (topLeftPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TopLeftPosition);
      }
      if (TopLeftHeight != 0F) {
        size += 1 + 4;
      }
      if (TopRightHeight != 0F) {
        size += 1 + 4;
      }
      if (BotLeftHeight != 0F) {
        size += 1 + 4;
      }
      if (BotRightHeight != 0F) {
        size += 1 + 4;
      }
      if (SplitDirection != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StBorderTile other) {
      if (other == null) {
        return;
      }
      if (other.TileTypeID != 0) {
        TileTypeID = other.TileTypeID;
      }
      if (other.topLeftPosition_ != null) {
        if (topLeftPosition_ == null) {
          topLeftPosition_ = new global::MHUrho.Storage.StIntVector2();
        }
        TopLeftPosition.MergeFrom(other.TopLeftPosition);
      }
      if (other.TopLeftHeight != 0F) {
        TopLeftHeight = other.TopLeftHeight;
      }
      if (other.TopRightHeight != 0F) {
        TopRightHeight = other.TopRightHeight;
      }
      if (other.BotLeftHeight != 0F) {
        BotLeftHeight = other.BotLeftHeight;
      }
      if (other.BotRightHeight != 0F) {
        BotRightHeight = other.BotRightHeight;
      }
      if (other.SplitDirection != false) {
        SplitDirection = other.SplitDirection;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TileTypeID = input.ReadInt32();
            break;
          }
          case 18: {
            if (topLeftPosition_ == null) {
              topLeftPosition_ = new global::MHUrho.Storage.StIntVector2();
            }
            input.ReadMessage(topLeftPosition_);
            break;
          }
          case 29: {
            TopLeftHeight = input.ReadFloat();
            break;
          }
          case 37: {
            TopRightHeight = input.ReadFloat();
            break;
          }
          case 45: {
            BotLeftHeight = input.ReadFloat();
            break;
          }
          case 53: {
            BotRightHeight = input.ReadFloat();
            break;
          }
          case 56: {
            SplitDirection = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class StMapTarget : pb::IMessage<StMapTarget> {
    private static readonly pb::MessageParser<StMapTarget> _parser = new pb::MessageParser<StMapTarget>(() => new StMapTarget());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StMapTarget> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MHUrho.Storage.GameStateReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StMapTarget() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StMapTarget(StMapTarget other) : this() {
      instanceID_ = other.instanceID_;
      Position = other.position_ != null ? other.Position.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StMapTarget Clone() {
      return new StMapTarget(this);
    }

    /// <summary>Field number for the "instanceID" field.</summary>
    public const int InstanceIDFieldNumber = 1;
    private int instanceID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int InstanceID {
      get { return instanceID_; }
      set {
        instanceID_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 2;
    private global::MHUrho.Storage.StVector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MHUrho.Storage.StVector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StMapTarget);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StMapTarget other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InstanceID != other.InstanceID) return false;
      if (!object.Equals(Position, other.Position)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (InstanceID != 0) hash ^= InstanceID.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (InstanceID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(InstanceID);
      }
      if (position_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Position);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (InstanceID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(InstanceID);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StMapTarget other) {
      if (other == null) {
        return;
      }
      if (other.InstanceID != 0) {
        InstanceID = other.InstanceID;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          position_ = new global::MHUrho.Storage.StVector3();
        }
        Position.MergeFrom(other.Position);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            InstanceID = input.ReadInt32();
            break;
          }
          case 18: {
            if (position_ == null) {
              position_ = new global::MHUrho.Storage.StVector3();
            }
            input.ReadMessage(position_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class StUnit : pb::IMessage<StUnit> {
    private static readonly pb::MessageParser<StUnit> _parser = new pb::MessageParser<StUnit>(() => new StUnit());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MHUrho.Storage.GameStateReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StUnit(StUnit other) : this() {
      id_ = other.id_;
      typeID_ = other.typeID_;
      Position = other.position_ != null ? other.Position.Clone() : null;
      playerID_ = other.playerID_;
      targetUnitID_ = other.targetUnitID_;
      UserPlugin = other.userPlugin_ != null ? other.UserPlugin.Clone() : null;
      defaultComponentData_ = other.defaultComponentData_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StUnit Clone() {
      return new StUnit(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "typeID" field.</summary>
    public const int TypeIDFieldNumber = 2;
    private int typeID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TypeID {
      get { return typeID_; }
      set {
        typeID_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 3;
    private global::MHUrho.Storage.StVector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MHUrho.Storage.StVector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "playerID" field.</summary>
    public const int PlayerIDFieldNumber = 4;
    private int playerID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerID {
      get { return playerID_; }
      set {
        playerID_ = value;
      }
    }

    /// <summary>Field number for the "targetUnitID" field.</summary>
    public const int TargetUnitIDFieldNumber = 5;
    private int targetUnitID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TargetUnitID {
      get { return targetUnitID_; }
      set {
        targetUnitID_ = value;
      }
    }

    /// <summary>Field number for the "userPlugin" field.</summary>
    public const int UserPluginFieldNumber = 6;
    private global::MHUrho.Storage.PluginData userPlugin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MHUrho.Storage.PluginData UserPlugin {
      get { return userPlugin_; }
      set {
        userPlugin_ = value;
      }
    }

    /// <summary>Field number for the "defaultComponentData" field.</summary>
    public const int DefaultComponentDataFieldNumber = 7;
    private static readonly pbc::MapField<int, global::MHUrho.Storage.PluginData>.Codec _map_defaultComponentData_codec
        = new pbc::MapField<int, global::MHUrho.Storage.PluginData>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForMessage(18, global::MHUrho.Storage.PluginData.Parser), 58);
    private readonly pbc::MapField<int, global::MHUrho.Storage.PluginData> defaultComponentData_ = new pbc::MapField<int, global::MHUrho.Storage.PluginData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::MHUrho.Storage.PluginData> DefaultComponentData {
      get { return defaultComponentData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (TypeID != other.TypeID) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (PlayerID != other.PlayerID) return false;
      if (TargetUnitID != other.TargetUnitID) return false;
      if (!object.Equals(UserPlugin, other.UserPlugin)) return false;
      if (!DefaultComponentData.Equals(other.DefaultComponentData)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (TypeID != 0) hash ^= TypeID.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (PlayerID != 0) hash ^= PlayerID.GetHashCode();
      if (TargetUnitID != 0) hash ^= TargetUnitID.GetHashCode();
      if (userPlugin_ != null) hash ^= UserPlugin.GetHashCode();
      hash ^= DefaultComponentData.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (TypeID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TypeID);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (PlayerID != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PlayerID);
      }
      if (TargetUnitID != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(TargetUnitID);
      }
      if (userPlugin_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(UserPlugin);
      }
      defaultComponentData_.WriteTo(output, _map_defaultComponentData_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (TypeID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TypeID);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (PlayerID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerID);
      }
      if (TargetUnitID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetUnitID);
      }
      if (userPlugin_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserPlugin);
      }
      size += defaultComponentData_.CalculateSize(_map_defaultComponentData_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StUnit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.TypeID != 0) {
        TypeID = other.TypeID;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          position_ = new global::MHUrho.Storage.StVector3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.PlayerID != 0) {
        PlayerID = other.PlayerID;
      }
      if (other.TargetUnitID != 0) {
        TargetUnitID = other.TargetUnitID;
      }
      if (other.userPlugin_ != null) {
        if (userPlugin_ == null) {
          userPlugin_ = new global::MHUrho.Storage.PluginData();
        }
        UserPlugin.MergeFrom(other.UserPlugin);
      }
      defaultComponentData_.Add(other.defaultComponentData_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            TypeID = input.ReadInt32();
            break;
          }
          case 26: {
            if (position_ == null) {
              position_ = new global::MHUrho.Storage.StVector3();
            }
            input.ReadMessage(position_);
            break;
          }
          case 32: {
            PlayerID = input.ReadInt32();
            break;
          }
          case 40: {
            TargetUnitID = input.ReadInt32();
            break;
          }
          case 50: {
            if (userPlugin_ == null) {
              userPlugin_ = new global::MHUrho.Storage.PluginData();
            }
            input.ReadMessage(userPlugin_);
            break;
          }
          case 58: {
            defaultComponentData_.AddEntriesFrom(input, _map_defaultComponentData_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class StProjectile : pb::IMessage<StProjectile> {
    private static readonly pb::MessageParser<StProjectile> _parser = new pb::MessageParser<StProjectile>(() => new StProjectile());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StProjectile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MHUrho.Storage.GameStateReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StProjectile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StProjectile(StProjectile other) : this() {
      id_ = other.id_;
      typeID_ = other.typeID_;
      Position = other.position_ != null ? other.Position.Clone() : null;
      playerID_ = other.playerID_;
      UserPlugin = other.userPlugin_ != null ? other.UserPlugin.Clone() : null;
      defaultComponentData_ = other.defaultComponentData_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StProjectile Clone() {
      return new StProjectile(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "typeID" field.</summary>
    public const int TypeIDFieldNumber = 2;
    private int typeID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TypeID {
      get { return typeID_; }
      set {
        typeID_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 3;
    private global::MHUrho.Storage.StVector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MHUrho.Storage.StVector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "playerID" field.</summary>
    public const int PlayerIDFieldNumber = 4;
    private int playerID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerID {
      get { return playerID_; }
      set {
        playerID_ = value;
      }
    }

    /// <summary>Field number for the "userPlugin" field.</summary>
    public const int UserPluginFieldNumber = 5;
    private global::MHUrho.Storage.PluginData userPlugin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MHUrho.Storage.PluginData UserPlugin {
      get { return userPlugin_; }
      set {
        userPlugin_ = value;
      }
    }

    /// <summary>Field number for the "defaultComponentData" field.</summary>
    public const int DefaultComponentDataFieldNumber = 6;
    private static readonly pbc::MapField<int, global::MHUrho.Storage.PluginData>.Codec _map_defaultComponentData_codec
        = new pbc::MapField<int, global::MHUrho.Storage.PluginData>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForMessage(18, global::MHUrho.Storage.PluginData.Parser), 50);
    private readonly pbc::MapField<int, global::MHUrho.Storage.PluginData> defaultComponentData_ = new pbc::MapField<int, global::MHUrho.Storage.PluginData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::MHUrho.Storage.PluginData> DefaultComponentData {
      get { return defaultComponentData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StProjectile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StProjectile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (TypeID != other.TypeID) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (PlayerID != other.PlayerID) return false;
      if (!object.Equals(UserPlugin, other.UserPlugin)) return false;
      if (!DefaultComponentData.Equals(other.DefaultComponentData)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (TypeID != 0) hash ^= TypeID.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (PlayerID != 0) hash ^= PlayerID.GetHashCode();
      if (userPlugin_ != null) hash ^= UserPlugin.GetHashCode();
      hash ^= DefaultComponentData.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (TypeID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TypeID);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (PlayerID != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PlayerID);
      }
      if (userPlugin_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(UserPlugin);
      }
      defaultComponentData_.WriteTo(output, _map_defaultComponentData_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (TypeID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TypeID);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (PlayerID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerID);
      }
      if (userPlugin_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserPlugin);
      }
      size += defaultComponentData_.CalculateSize(_map_defaultComponentData_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StProjectile other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.TypeID != 0) {
        TypeID = other.TypeID;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          position_ = new global::MHUrho.Storage.StVector3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.PlayerID != 0) {
        PlayerID = other.PlayerID;
      }
      if (other.userPlugin_ != null) {
        if (userPlugin_ == null) {
          userPlugin_ = new global::MHUrho.Storage.PluginData();
        }
        UserPlugin.MergeFrom(other.UserPlugin);
      }
      defaultComponentData_.Add(other.defaultComponentData_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            TypeID = input.ReadInt32();
            break;
          }
          case 26: {
            if (position_ == null) {
              position_ = new global::MHUrho.Storage.StVector3();
            }
            input.ReadMessage(position_);
            break;
          }
          case 32: {
            PlayerID = input.ReadInt32();
            break;
          }
          case 42: {
            if (userPlugin_ == null) {
              userPlugin_ = new global::MHUrho.Storage.PluginData();
            }
            input.ReadMessage(userPlugin_);
            break;
          }
          case 50: {
            defaultComponentData_.AddEntriesFrom(input, _map_defaultComponentData_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class StBuilding : pb::IMessage<StBuilding> {
    private static readonly pb::MessageParser<StBuilding> _parser = new pb::MessageParser<StBuilding>(() => new StBuilding());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StBuilding> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MHUrho.Storage.GameStateReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StBuilding() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StBuilding(StBuilding other) : this() {
      id_ = other.id_;
      typeID_ = other.typeID_;
      Location = other.location_ != null ? other.Location.Clone() : null;
      playerID_ = other.playerID_;
      UserPlugin = other.userPlugin_ != null ? other.UserPlugin.Clone() : null;
      defaultComponentData_ = other.defaultComponentData_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StBuilding Clone() {
      return new StBuilding(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "typeID" field.</summary>
    public const int TypeIDFieldNumber = 2;
    private int typeID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TypeID {
      get { return typeID_; }
      set {
        typeID_ = value;
      }
    }

    /// <summary>Field number for the "location" field.</summary>
    public const int LocationFieldNumber = 3;
    private global::MHUrho.Storage.StIntVector2 location_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MHUrho.Storage.StIntVector2 Location {
      get { return location_; }
      set {
        location_ = value;
      }
    }

    /// <summary>Field number for the "playerID" field.</summary>
    public const int PlayerIDFieldNumber = 4;
    private int playerID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerID {
      get { return playerID_; }
      set {
        playerID_ = value;
      }
    }

    /// <summary>Field number for the "userPlugin" field.</summary>
    public const int UserPluginFieldNumber = 6;
    private global::MHUrho.Storage.PluginData userPlugin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MHUrho.Storage.PluginData UserPlugin {
      get { return userPlugin_; }
      set {
        userPlugin_ = value;
      }
    }

    /// <summary>Field number for the "defaultComponentData" field.</summary>
    public const int DefaultComponentDataFieldNumber = 7;
    private static readonly pbc::MapField<int, global::MHUrho.Storage.PluginData>.Codec _map_defaultComponentData_codec
        = new pbc::MapField<int, global::MHUrho.Storage.PluginData>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForMessage(18, global::MHUrho.Storage.PluginData.Parser), 58);
    private readonly pbc::MapField<int, global::MHUrho.Storage.PluginData> defaultComponentData_ = new pbc::MapField<int, global::MHUrho.Storage.PluginData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::MHUrho.Storage.PluginData> DefaultComponentData {
      get { return defaultComponentData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StBuilding);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StBuilding other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (TypeID != other.TypeID) return false;
      if (!object.Equals(Location, other.Location)) return false;
      if (PlayerID != other.PlayerID) return false;
      if (!object.Equals(UserPlugin, other.UserPlugin)) return false;
      if (!DefaultComponentData.Equals(other.DefaultComponentData)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (TypeID != 0) hash ^= TypeID.GetHashCode();
      if (location_ != null) hash ^= Location.GetHashCode();
      if (PlayerID != 0) hash ^= PlayerID.GetHashCode();
      if (userPlugin_ != null) hash ^= UserPlugin.GetHashCode();
      hash ^= DefaultComponentData.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (TypeID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TypeID);
      }
      if (location_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Location);
      }
      if (PlayerID != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PlayerID);
      }
      if (userPlugin_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(UserPlugin);
      }
      defaultComponentData_.WriteTo(output, _map_defaultComponentData_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (TypeID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TypeID);
      }
      if (location_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Location);
      }
      if (PlayerID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerID);
      }
      if (userPlugin_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserPlugin);
      }
      size += defaultComponentData_.CalculateSize(_map_defaultComponentData_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StBuilding other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.TypeID != 0) {
        TypeID = other.TypeID;
      }
      if (other.location_ != null) {
        if (location_ == null) {
          location_ = new global::MHUrho.Storage.StIntVector2();
        }
        Location.MergeFrom(other.Location);
      }
      if (other.PlayerID != 0) {
        PlayerID = other.PlayerID;
      }
      if (other.userPlugin_ != null) {
        if (userPlugin_ == null) {
          userPlugin_ = new global::MHUrho.Storage.PluginData();
        }
        UserPlugin.MergeFrom(other.UserPlugin);
      }
      defaultComponentData_.Add(other.defaultComponentData_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            TypeID = input.ReadInt32();
            break;
          }
          case 26: {
            if (location_ == null) {
              location_ = new global::MHUrho.Storage.StIntVector2();
            }
            input.ReadMessage(location_);
            break;
          }
          case 32: {
            PlayerID = input.ReadInt32();
            break;
          }
          case 50: {
            if (userPlugin_ == null) {
              userPlugin_ = new global::MHUrho.Storage.PluginData();
            }
            input.ReadMessage(userPlugin_);
            break;
          }
          case 58: {
            defaultComponentData_.AddEntriesFrom(input, _map_defaultComponentData_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class StPlayer : pb::IMessage<StPlayer> {
    private static readonly pb::MessageParser<StPlayer> _parser = new pb::MessageParser<StPlayer>(() => new StPlayer());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StPlayer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MHUrho.Storage.GameStateReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StPlayer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StPlayer(StPlayer other) : this() {
      playerID_ = other.playerID_;
      unitIDs_ = other.unitIDs_.Clone();
      buildingIDs_ = other.buildingIDs_.Clone();
      friendPlayerIDs_ = other.friendPlayerIDs_.Clone();
      UserPlugin = other.userPlugin_ != null ? other.UserPlugin.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StPlayer Clone() {
      return new StPlayer(this);
    }

    /// <summary>Field number for the "playerID" field.</summary>
    public const int PlayerIDFieldNumber = 1;
    private int playerID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerID {
      get { return playerID_; }
      set {
        playerID_ = value;
      }
    }

    /// <summary>Field number for the "unitIDs" field.</summary>
    public const int UnitIDsFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_unitIDs_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> unitIDs_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///TODO: Redundant references both ways, could just store it in building/unit and connect it from there
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> UnitIDs {
      get { return unitIDs_; }
    }

    /// <summary>Field number for the "buildingIDs" field.</summary>
    public const int BuildingIDsFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_buildingIDs_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> buildingIDs_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> BuildingIDs {
      get { return buildingIDs_; }
    }

    /// <summary>Field number for the "friendPlayerIDs" field.</summary>
    public const int FriendPlayerIDsFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_friendPlayerIDs_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> friendPlayerIDs_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> FriendPlayerIDs {
      get { return friendPlayerIDs_; }
    }

    /// <summary>Field number for the "userPlugin" field.</summary>
    public const int UserPluginFieldNumber = 5;
    private global::MHUrho.Storage.PluginData userPlugin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MHUrho.Storage.PluginData UserPlugin {
      get { return userPlugin_; }
      set {
        userPlugin_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StPlayer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StPlayer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerID != other.PlayerID) return false;
      if(!unitIDs_.Equals(other.unitIDs_)) return false;
      if(!buildingIDs_.Equals(other.buildingIDs_)) return false;
      if(!friendPlayerIDs_.Equals(other.friendPlayerIDs_)) return false;
      if (!object.Equals(UserPlugin, other.UserPlugin)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerID != 0) hash ^= PlayerID.GetHashCode();
      hash ^= unitIDs_.GetHashCode();
      hash ^= buildingIDs_.GetHashCode();
      hash ^= friendPlayerIDs_.GetHashCode();
      if (userPlugin_ != null) hash ^= UserPlugin.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerID);
      }
      unitIDs_.WriteTo(output, _repeated_unitIDs_codec);
      buildingIDs_.WriteTo(output, _repeated_buildingIDs_codec);
      friendPlayerIDs_.WriteTo(output, _repeated_friendPlayerIDs_codec);
      if (userPlugin_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(UserPlugin);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerID);
      }
      size += unitIDs_.CalculateSize(_repeated_unitIDs_codec);
      size += buildingIDs_.CalculateSize(_repeated_buildingIDs_codec);
      size += friendPlayerIDs_.CalculateSize(_repeated_friendPlayerIDs_codec);
      if (userPlugin_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserPlugin);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StPlayer other) {
      if (other == null) {
        return;
      }
      if (other.PlayerID != 0) {
        PlayerID = other.PlayerID;
      }
      unitIDs_.Add(other.unitIDs_);
      buildingIDs_.Add(other.buildingIDs_);
      friendPlayerIDs_.Add(other.friendPlayerIDs_);
      if (other.userPlugin_ != null) {
        if (userPlugin_ == null) {
          userPlugin_ = new global::MHUrho.Storage.PluginData();
        }
        UserPlugin.MergeFrom(other.UserPlugin);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            PlayerID = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            unitIDs_.AddEntriesFrom(input, _repeated_unitIDs_codec);
            break;
          }
          case 26:
          case 24: {
            buildingIDs_.AddEntriesFrom(input, _repeated_buildingIDs_codec);
            break;
          }
          case 34:
          case 32: {
            friendPlayerIDs_.AddEntriesFrom(input, _repeated_friendPlayerIDs_codec);
            break;
          }
          case 42: {
            if (userPlugin_ == null) {
              userPlugin_ = new global::MHUrho.Storage.PluginData();
            }
            input.ReadMessage(userPlugin_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class StMap : pb::IMessage<StMap> {
    private static readonly pb::MessageParser<StMap> _parser = new pb::MessageParser<StMap>(() => new StMap());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StMap> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MHUrho.Storage.GameStateReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StMap() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StMap(StMap other) : this() {
      Size = other.size_ != null ? other.Size.Clone() : null;
      tiles_ = other.tiles_.Clone();
      borderTiles_ = other.borderTiles_.Clone();
      mapRangeTargets_ = other.mapRangeTargets_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StMap Clone() {
      return new StMap(this);
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 1;
    private global::MHUrho.Storage.StIntVector2 size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MHUrho.Storage.StIntVector2 Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "tiles" field.</summary>
    public const int TilesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::MHUrho.Storage.StTile> _repeated_tiles_codec
        = pb::FieldCodec.ForMessage(18, global::MHUrho.Storage.StTile.Parser);
    private readonly pbc::RepeatedField<global::MHUrho.Storage.StTile> tiles_ = new pbc::RepeatedField<global::MHUrho.Storage.StTile>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MHUrho.Storage.StTile> Tiles {
      get { return tiles_; }
    }

    /// <summary>Field number for the "borderTiles" field.</summary>
    public const int BorderTilesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::MHUrho.Storage.StBorderTile> _repeated_borderTiles_codec
        = pb::FieldCodec.ForMessage(26, global::MHUrho.Storage.StBorderTile.Parser);
    private readonly pbc::RepeatedField<global::MHUrho.Storage.StBorderTile> borderTiles_ = new pbc::RepeatedField<global::MHUrho.Storage.StBorderTile>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MHUrho.Storage.StBorderTile> BorderTiles {
      get { return borderTiles_; }
    }

    /// <summary>Field number for the "mapRangeTargets" field.</summary>
    public const int MapRangeTargetsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::MHUrho.Storage.StMapTarget> _repeated_mapRangeTargets_codec
        = pb::FieldCodec.ForMessage(34, global::MHUrho.Storage.StMapTarget.Parser);
    private readonly pbc::RepeatedField<global::MHUrho.Storage.StMapTarget> mapRangeTargets_ = new pbc::RepeatedField<global::MHUrho.Storage.StMapTarget>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MHUrho.Storage.StMapTarget> MapRangeTargets {
      get { return mapRangeTargets_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StMap);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StMap other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Size, other.Size)) return false;
      if(!tiles_.Equals(other.tiles_)) return false;
      if(!borderTiles_.Equals(other.borderTiles_)) return false;
      if(!mapRangeTargets_.Equals(other.mapRangeTargets_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (size_ != null) hash ^= Size.GetHashCode();
      hash ^= tiles_.GetHashCode();
      hash ^= borderTiles_.GetHashCode();
      hash ^= mapRangeTargets_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (size_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Size);
      }
      tiles_.WriteTo(output, _repeated_tiles_codec);
      borderTiles_.WriteTo(output, _repeated_borderTiles_codec);
      mapRangeTargets_.WriteTo(output, _repeated_mapRangeTargets_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (size_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Size);
      }
      size += tiles_.CalculateSize(_repeated_tiles_codec);
      size += borderTiles_.CalculateSize(_repeated_borderTiles_codec);
      size += mapRangeTargets_.CalculateSize(_repeated_mapRangeTargets_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StMap other) {
      if (other == null) {
        return;
      }
      if (other.size_ != null) {
        if (size_ == null) {
          size_ = new global::MHUrho.Storage.StIntVector2();
        }
        Size.MergeFrom(other.Size);
      }
      tiles_.Add(other.tiles_);
      borderTiles_.Add(other.borderTiles_);
      mapRangeTargets_.Add(other.mapRangeTargets_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (size_ == null) {
              size_ = new global::MHUrho.Storage.StIntVector2();
            }
            input.ReadMessage(size_);
            break;
          }
          case 18: {
            tiles_.AddEntriesFrom(input, _repeated_tiles_codec);
            break;
          }
          case 26: {
            borderTiles_.AddEntriesFrom(input, _repeated_borderTiles_codec);
            break;
          }
          case 34: {
            mapRangeTargets_.AddEntriesFrom(input, _repeated_mapRangeTargets_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
